### ISSUE TITLE
Ubuntu 18.04, cannot update wgX.conf file

### ISSUE THREAD

**Issue by dragon2611** [spacedog/puppet-wireguard#12]
It appears on my ubuntu 18.04 vm at least puppet cannot update the file (e.g wg0.conf) if wireguard is actually running at the time.

What happens is puppet reports it replaced the file but when you check the file it appears to be the old version, I think it's something to do with wg-quick that's causing it but I'm not 100% on that.
This leads to the puppet agent repeatedly trying to replace the file every-time puppet runs because the MD5 doesn't match with the one on the puppet master.

**Comment by spacedog** [comment]
@dragon2611 : thank you for opening the issue. Could you please share configuration you use ?
To debug more you could also set show_diff => true for  interface file to see what exactly is changing

**Comment by dragon2611** [comment]
@spacedog Sorry that's my fault for not being clear about the problem.

To Reproduce:
Where X is the interface we want to configure.

1) Configure a new Wireguard interface using the wireguard module
2) run puppet, config is deployed successfully and wg-quick@wgX is started
3) Change something on the puppet master (e.g add a new peer)
4) Run the puppet agent or wait for it to next run.

Expected Result.

Config is updated with the changes from the puppet master.

Actual Result.

Previously deployed config is still in place,

Further details:

When run with puppet agent -t puppet reports the config file changed and provides the MD5 for both the old and new File but the old version of the WGx.conf (in /etc/wireguard if you haven't changed the default path) remains.

If I stop the wg-quick@WgX manually and then run puppet the config file is updated successfully and wireguard is started with the new config.

My guess is something is locking the file when the service is running.

**Comment by dragon2611** [comment]
Not sure if this is the best way to do it, but it does seem to resolve the problem for me, I'm also not 100% sure why puppet can't change the file when the service is running given I appear to be able to make manual edits. https://github.com/spacedog/puppet-wireguard/pull/13

Apologies in advance if I've missed something, I'm not a developer and I'm fairly new to puppet.

**Comment by spacedog** [comment]
Could you try to set `saveconfig => false` for wg interface ?

> SaveConfig — if set to `true', the configuration is saved from the current state of the interface upon shutdown.

**Comment by dragon2611** [comment]
Yep that does it and much more elegant than the solution I came up with.
