### ISSUE TITLE
Ubuntu 20.04 LTS: Do not install from PPA

### ISSUE THREAD

**Issue by raoulbhatia** [spacedog/puppet-wireguard#28]
HI,

Ubuntu 20.04 LTS ships WireGuard as part of the `linux-modules-5.4.0-*-generic` package.

Would it make sense to modify the defaults to not install from PPA (and other third party repositories) for Ubuntu 20.04+ / kernel 5.6+?

Thanks,
Raoul

**Comment by spacedog** [comment]
Fixed in #31

**Comment by raoulbhatia** [comment]
Cool, thanks!  🇬🇧
