### ISSUE TITLE
Release on Puppet Forge includes .git directory

### ISSUE THREAD

**Issue by raoulbhatia** [spacedog/puppet-wireguard#36]
Hi,

the release you published on Puppet Forge includes the .git directory (and potentially other, unrelated files), see

```
$ wget https://forge.puppet.com/v3/files/abaranov-wireguard-0.4.4.tar.gz
$ tar tvzf abaranov-wireguard-0.4.4.tar.gz  | grep '/\.git/' | wc -l
673
```

Cheers,
Raoul

**Comment by spacedog** [comment]
Fixed : https://github.com/spacedog/puppet-wireguard/commit/880207619169ee283fa676a8578607bf19c93def
