### ISSUE TITLE
Debian - do not install from unstable

### ISSUE THREAD

**Issue by micah** [spacedog/puppet-wireguard#39]
The `install.pp` on https://github.com/spacedog/puppet-wireguard/blob/master/manifests/install.pp#L33 requires the `apt` module and then sets up a pin for debian unstable.

There is no need to install this from unstable, the wireguard packages in stable work fine.

**Comment by PandemiK911** [comment]
It would be a nice thing (aka +1)
In the mean time, you can set manage_repo to false so the debian_unstable repo won't be added.

**Comment by spacedog** [comment]
Fixed in #41
